name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cd language-server && npm ci
    - run: cd language-server && npm test
    - run: cd language-server && npm run type-check
    - run: cd language-server && npm run lint
    - run: cd vscode && npm ci
    - run: cd vscode && npm run type-check
    - run: cd vscode && npm run lint
    - run: cd vscode && npm run build
